apiVersion: v1
kind: Secret
metadata:
  name: devsecops-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  github-token:              "{{ .Values.secrets.githubToken }}"
  gitlab-token:              "{{ .Values.secrets.gitlabToken }}"
  github-webhook-secret:     "{{ .Values.secrets.githubWebhookSecret }}"
  gitlab-webhook-secret:     "{{ .Values.secrets.gitlabWebhookSecret }}"
  ai-api-key:                "{{ .Values.secrets.aiApiKey }}"
  results-bucket:            "{{ .Values.secrets.resultsBucket }}"
  defectdojo-url:            "{{ .Values.secrets.defectdojoUrl }}"
  defectdojo-token:          "{{ .Values.secrets.defectdojoToken }}"
  aws-access-key-id:         "{{ .Values.secrets.awsAccessKeyId }}"
  aws-secret-access-key:     "{{ .Values.secrets.awsSecretAccessKey }}"
  aws-default-region:        "{{ .Values.secrets.awsDefaultRegion }}"
  azure-storage-conn-string: "{{ .Values.secrets.azureStorageConnectionString }}"
  slack-webhook-url:         "{{ .Values.secrets.slackWebhookUrl }}"
